### ISSUE TITLE
Support of Safari, and light mode.

### ISSUE THREAD

**Issue by umnovmax** [314tonick/ejudge-lksh-plus#1]
It doesn't work on safari, add it on it + where is light mode + Why so big files?

**Comment by umnovmax** [comment]
+ You didn't answer on it, write obyasnitelnaya

**Comment by umnovmax** [comment]
I give you 0 stars, I waited more than 1 second for the answer

**Comment by 314tonick** [comment]
* You can add support of Safari by creating fork of it. I think than difference is only, that you need to change manifest.json, storager.json and service.json. Only them use chrome.runtime interface.
* Light mode will be added later (may be).
* Code files are not big. Images files are big, because they have high resolution.

**Comment by umnovmax** [comment]
1. ok, but UwU
2. ok, but you need to add UwU
3. You WILL add UwU
4. Or I will add UwU
5. or I will UwU UwU

**Comment by umnovmax** [comment]
ok, but UwU
ok, but you need to add UwU
You WILL add UwU
Or I will add UwU
or I will UwU UwU

**Comment by 314tonick** [comment]
Please not spam, else you will get banned from me/github.
